apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: verim

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - db.yaml
  - redpanda.yaml
  - graphdb.yaml
  - opensearch.yaml
  - jobs.yaml
  - sources.yaml
  - ingest.yaml
  - reasoning.yaml
  - app.yaml
  - ingress.yaml

# İmajı kendi registry'ne çevirmek için tek nokta:
images:
  - name: verim-app
    newName: verim-app # ör. europe-west1-docker.pkg.dev/PROJE/verim/app
    newTag: latest
