import { Injectable } from '@nestjs/common';
import type { OntologyResponse } from '../contract/mercek';
import type { OntologyProvider } from './ontology-provider';

/**
 * All Domain Joint C2 dummy ontolojisi — MIP information model'in yerini
 * alacak port implementasyonu. İlişkiler iki yönlü tanımlı; "search
 * around" zincirleri: İz → Sensör → Platform → Birlik → Görevler.
 */
@Injectable()
export class DummyOntologyProvider implements OntologyProvider {
  getOntology(): Promise<OntologyResponse> {
    return Promise.resolve({
      objectTypes: [
        {
          apiName: 'birlik',
          displayName: 'Birlik',
          pluralName: 'Birlikler',
          icon: '🎖️',
          primaryKey: 'birlik_no',
          datasetId: 'birlikler',
          properties: [
            { apiName: 'birlik_no', displayName: 'Birlik No', type: 'string' },
            { apiName: 'ad', displayName: 'Ad', type: 'string' },
            { apiName: 'domain', displayName: 'Domain', type: 'string' },
            { apiName: 'kademe', displayName: 'Kademe', type: 'string' },
            { apiName: 'bolge', displayName: 'Bölge', type: 'string' },
            { apiName: 'durum', displayName: 'Durum', type: 'string' },
            { apiName: 'personel', displayName: 'Personel', type: 'integer' },
            { apiName: 'hazirlik_orani', displayName: 'Hazırlık Oranı', type: 'integer' },
            { apiName: 'komutan_no', displayName: 'Komutan', type: 'string' },
            { apiName: 'us_adi', displayName: 'Üs / Garnizon', type: 'string' },
          ],
        },
        {
          apiName: 'platform',
          displayName: 'Platform',
          pluralName: 'Platformlar',
          icon: '🛩️',
          primaryKey: 'platform_no',
          datasetId: 'platformlar',
          properties: [
            { apiName: 'platform_no', displayName: 'Platform No', type: 'string' },
            { apiName: 'cagri_adi', displayName: 'Çağrı Adı', type: 'string' },
            { apiName: 'tip', displayName: 'Tip', type: 'string' },
            { apiName: 'domain', displayName: 'Domain', type: 'string' },
            { apiName: 'birlik_no', displayName: 'Bağlı Birlik', type: 'string' },
            { apiName: 'durum', displayName: 'Durum', type: 'string' },
            { apiName: 'yakit_orani', displayName: 'Yakıt Oranı', type: 'integer' },
            { apiName: 'surat_knot', displayName: 'Sürat (knot)', type: 'integer' },
            { apiName: 'enlem', displayName: 'Enlem', type: 'double' },
            { apiName: 'boylam', displayName: 'Boylam', type: 'double' },
            { apiName: 'kuyruk_no', displayName: 'Kuyruk No', type: 'string' },
            { apiName: 'uretici', displayName: 'Üretici', type: 'string' },
          ],
        },
        {
          apiName: 'gorev',
          displayName: 'Görev',
          pluralName: 'Görevler',
          icon: '🎯',
          primaryKey: 'gorev_no',
          datasetId: 'gorevler',
          properties: [
            { apiName: 'gorev_no', displayName: 'Görev No', type: 'string' },
            { apiName: 'tip', displayName: 'Tip', type: 'string' },
            { apiName: 'durum', displayName: 'Durum', type: 'string' },
            { apiName: 'oncelik', displayName: 'Öncelik', type: 'integer' },
            { apiName: 'baslangic', displayName: 'Başlangıç', type: 'timestamp' },
            { apiName: 'sure_saat', displayName: 'Süre (saat)', type: 'integer' },
            { apiName: 'birlik_no', displayName: 'İcra Eden Birlik', type: 'string' },
            { apiName: 'domain', displayName: 'Domain', type: 'string' },
            { apiName: 'basari_puani', displayName: 'Başarı Puanı', type: 'integer' },
            { apiName: 'hedef_bolge', displayName: 'Hedef Bölge', type: 'string' },
            { apiName: 'komutan_no', displayName: 'Görev Komutanı', type: 'string' },
          ],
        },
        {
          apiName: 'sensor',
          displayName: 'Sensör',
          pluralName: 'Sensörler',
          icon: '📡',
          primaryKey: 'sensor_no',
          datasetId: 'sensorler',
          properties: [
            { apiName: 'sensor_no', displayName: 'Sensör No', type: 'string' },
            { apiName: 'tip', displayName: 'Tip', type: 'string' },
            { apiName: 'platform_no', displayName: 'Takılı Platform', type: 'string' },
            { apiName: 'menzil_km', displayName: 'Menzil (km)', type: 'integer' },
            { apiName: 'durum', displayName: 'Durum', type: 'string' },
            { apiName: 'uretici', displayName: 'Üretici', type: 'string' },
            { apiName: 'frekans_bandi', displayName: 'Frekans Bandı', type: 'string' },
          ],
        },
        {
          apiName: 'iz',
          displayName: 'İz',
          pluralName: 'İzler',
          icon: '🛰️',
          primaryKey: 'iz_no',
          datasetId: 'izler',
          properties: [
            { apiName: 'iz_no', displayName: 'İz No', type: 'string' },
            { apiName: 'siniflandirma', displayName: 'Sınıflandırma', type: 'string' },
            { apiName: 'domain', displayName: 'Domain', type: 'string' },
            { apiName: 'tespit_zamani', displayName: 'Tespit Zamanı', type: 'timestamp' },
            { apiName: 'sensor_no', displayName: 'Tespit Eden Sensör', type: 'string' },
            { apiName: 'surat_knot', displayName: 'Sürat (knot)', type: 'integer' },
            { apiName: 'irtifa_ft', displayName: 'İrtifa (ft)', type: 'integer' },
            { apiName: 'rota_derece', displayName: 'Rota (°)', type: 'integer' },
            { apiName: 'enlem', displayName: 'Enlem', type: 'double' },
            { apiName: 'boylam', displayName: 'Boylam', type: 'double' },
            { apiName: 'tehdit_seviyesi', displayName: 'Tehdit Seviyesi', type: 'integer' },
            { apiName: 'tehdit_skoru', displayName: 'Tehdit Skoru', type: 'integer' },
            { apiName: 'tehdit_onceligi', displayName: 'Tehdit Önceliği', type: 'string' },
            { apiName: 'yaklasiyor', displayName: 'Yaklaşıyor', type: 'boolean' },
          ],
        },
        {
          apiName: 'iz_gozlem',
          displayName: 'İz Gözlemi',
          pluralName: 'İz Gözlemleri',
          icon: '🔭',
          primaryKey: 'gozlem_no',
          datasetId: 'iz_gecmisi',
          properties: [
            { apiName: 'gozlem_no', displayName: 'Gözlem No', type: 'string' },
            { apiName: 'iz_no', displayName: 'İz No', type: 'string' },
            { apiName: 'tespit_zamani', displayName: 'Tespit Zamanı', type: 'timestamp' },
            { apiName: 'sensor_no', displayName: 'Tespit Eden Sensör', type: 'string' },
            { apiName: 'domain', displayName: 'Domain', type: 'string' },
            { apiName: 'tehdit_seviyesi', displayName: 'Tehdit Seviyesi', type: 'integer' },
            { apiName: 'enlem', displayName: 'Enlem', type: 'double' },
            { apiName: 'boylam', displayName: 'Boylam', type: 'double' },
            { apiName: 'surat_knot', displayName: 'Sürat (knot)', type: 'integer' },
            { apiName: 'irtifa_ft', displayName: 'İrtifa (ft)', type: 'integer' },
            { apiName: 'rota_derece', displayName: 'Rota (°)', type: 'integer' },
          ],
        },
        {
          apiName: 'istihbarat_raporu',
          displayName: 'İstihbarat Raporu',
          pluralName: 'İstihbarat Raporları',
          icon: '🕵️',
          primaryKey: 'rapor_no',
          datasetId: 'istihbarat',
          properties: [
            { apiName: 'rapor_no', displayName: 'Rapor No', type: 'string' },
            { apiName: 'tur', displayName: 'Tür (INT disiplini)', type: 'string' },
            { apiName: 'baslik', displayName: 'Başlık', type: 'string' },
            { apiName: 'ozet', displayName: 'Özet', type: 'string' },
            { apiName: 'kaynak', displayName: 'Kaynak', type: 'string' },
            { apiName: 'kaynak_guvenilirligi', displayName: 'Kaynak Güvenilirliği (A–F)', type: 'string' },
            { apiName: 'bilgi_dogrulugu', displayName: 'Bilgi Doğruluğu (1–6)', type: 'integer' },
            { apiName: 'oncelik', displayName: 'Öncelik', type: 'string' },
            { apiName: 'tehdit_tipi', displayName: 'Tehdit / Konu', type: 'string' },
            { apiName: 'guven_yuzde', displayName: 'Güven (%)', type: 'integer' },
            { apiName: 'ilgili_iz_no', displayName: 'İlgili İz', type: 'string' },
            { apiName: 'enlem', displayName: 'Enlem', type: 'double' },
            { apiName: 'boylam', displayName: 'Boylam', type: 'double' },
            { apiName: 'rapor_zamani', displayName: 'Rapor Zamanı', type: 'timestamp' },
          ],
        },
        {
          apiName: 'personel',
          displayName: 'Personel',
          pluralName: 'Personel',
          icon: '🪖',
          primaryKey: 'personel_no',
          datasetId: 'personel',
          properties: [
            { apiName: 'personel_no', displayName: 'Personel No', type: 'string' },
            { apiName: 'ad_soyad', displayName: 'Ad Soyad', type: 'string' },
            { apiName: 'rutbe', displayName: 'Rütbe', type: 'string' },
            { apiName: 'rutbe_seviye', displayName: 'Rütbe Seviyesi', type: 'integer' },
            { apiName: 'rol', displayName: 'Görev / Rol', type: 'string' },
            { apiName: 'uzmanlik', displayName: 'Uzmanlık', type: 'string' },
            { apiName: 'birlik_no', displayName: 'Mensup Birlik', type: 'string' },
            { apiName: 'platform_no', displayName: 'Görevli Platform', type: 'string' },
            { apiName: 'durum', displayName: 'Durum', type: 'string' },
            { apiName: 'guvenlik_belgesi', displayName: 'Güvenlik Belgesi', type: 'string' },
            { apiName: 'tecrube_yili', displayName: 'Tecrübe (yıl)', type: 'integer' },
            { apiName: 'ucus_saati', displayName: 'Uçuş Saati', type: 'integer' },
          ],
        },
      ],
      linkTypes: [
        {
          apiName: 'platform-birlik',
          displayName: 'Bağlı olduğu birlik',
          fromObjectType: 'platform',
          toObjectType: 'birlik',
          cardinality: 'one',
          fromKey: 'birlik_no',
          toKey: 'birlik_no',
        },
        {
          apiName: 'birlik-platformlar',
          displayName: 'Birliğin platformları',
          fromObjectType: 'birlik',
          toObjectType: 'platform',
          cardinality: 'many',
          fromKey: 'birlik_no',
          toKey: 'birlik_no',
        },
        {
          apiName: 'gorev-birlik',
          displayName: 'Görevi icra eden birlik',
          fromObjectType: 'gorev',
          toObjectType: 'birlik',
          cardinality: 'one',
          fromKey: 'birlik_no',
          toKey: 'birlik_no',
        },
        {
          apiName: 'birlik-gorevler',
          displayName: 'Birliğin görevleri',
          fromObjectType: 'birlik',
          toObjectType: 'gorev',
          cardinality: 'many',
          fromKey: 'birlik_no',
          toKey: 'birlik_no',
        },
        {
          apiName: 'sensor-platform',
          displayName: 'Takılı olduğu platform',
          fromObjectType: 'sensor',
          toObjectType: 'platform',
          cardinality: 'one',
          fromKey: 'platform_no',
          toKey: 'platform_no',
        },
        {
          apiName: 'platform-sensorler',
          displayName: 'Platformun sensörleri',
          fromObjectType: 'platform',
          toObjectType: 'sensor',
          cardinality: 'many',
          fromKey: 'platform_no',
          toKey: 'platform_no',
        },
        {
          apiName: 'iz-sensor',
          displayName: 'Tespit eden sensör',
          fromObjectType: 'iz',
          toObjectType: 'sensor',
          cardinality: 'one',
          fromKey: 'sensor_no',
          toKey: 'sensor_no',
        },
        {
          apiName: 'iz-gozlemler',
          displayName: 'İzin gözlem geçmişi',
          fromObjectType: 'iz',
          toObjectType: 'iz_gozlem',
          cardinality: 'many',
          fromKey: 'iz_no',
          toKey: 'iz_no',
        },
        {
          apiName: 'gozlem-iz',
          displayName: 'Gözlemin izi',
          fromObjectType: 'iz_gozlem',
          toObjectType: 'iz',
          cardinality: 'one',
          fromKey: 'iz_no',
          toKey: 'iz_no',
        },
        {
          apiName: 'gozlem-sensor',
          displayName: 'Gözlemi yapan sensör',
          fromObjectType: 'iz_gozlem',
          toObjectType: 'sensor',
          cardinality: 'one',
          fromKey: 'sensor_no',
          toKey: 'sensor_no',
        },
        {
          apiName: 'sensor-gozlemler',
          displayName: 'Sensörün gözlemleri',
          fromObjectType: 'sensor',
          toObjectType: 'iz_gozlem',
          cardinality: 'many',
          fromKey: 'sensor_no',
          toKey: 'sensor_no',
        },
        {
          apiName: 'sensor-izler',
          displayName: 'Sensörün tespit ettiği izler',
          fromObjectType: 'sensor',
          toObjectType: 'iz',
          cardinality: 'many',
          fromKey: 'sensor_no',
          toKey: 'sensor_no',
        },
        {
          apiName: 'personel-birlik',
          displayName: 'Mensup olduğu birlik',
          fromObjectType: 'personel',
          toObjectType: 'birlik',
          cardinality: 'one',
          fromKey: 'birlik_no',
          toKey: 'birlik_no',
        },
        {
          apiName: 'birlik-personeller',
          displayName: 'Birliğin personeli',
          fromObjectType: 'birlik',
          toObjectType: 'personel',
          cardinality: 'many',
          fromKey: 'birlik_no',
          toKey: 'birlik_no',
        },
        {
          apiName: 'personel-platform',
          displayName: 'Görevli olduğu platform',
          fromObjectType: 'personel',
          toObjectType: 'platform',
          cardinality: 'one',
          fromKey: 'platform_no',
          toKey: 'platform_no',
        },
        {
          apiName: 'platform-personeller',
          displayName: 'Platform mürettebatı',
          fromObjectType: 'platform',
          toObjectType: 'personel',
          cardinality: 'many',
          fromKey: 'platform_no',
          toKey: 'platform_no',
        },
        {
          apiName: 'rapor-iz',
          displayName: 'İlgili iz',
          fromObjectType: 'istihbarat_raporu',
          toObjectType: 'iz',
          cardinality: 'one',
          fromKey: 'ilgili_iz_no',
          toKey: 'iz_no',
        },
        {
          apiName: 'iz-raporlar',
          displayName: 'İze bağlı istihbarat',
          fromObjectType: 'iz',
          toObjectType: 'istihbarat_raporu',
          cardinality: 'many',
          fromKey: 'iz_no',
          toKey: 'ilgili_iz_no',
        },
        {
          apiName: 'birlik-komutan',
          displayName: 'Birliğin komutanı',
          fromObjectType: 'birlik',
          toObjectType: 'personel',
          cardinality: 'one',
          fromKey: 'komutan_no',
          toKey: 'personel_no',
        },
        {
          apiName: 'gorev-komutan',
          displayName: 'Görev komutanı',
          fromObjectType: 'gorev',
          toObjectType: 'personel',
          cardinality: 'one',
          fromKey: 'komutan_no',
          toKey: 'personel_no',
        },
      ],
    });
  }
}
